# .github/workflows/deploy.yml
name: Deploy sabIA to Firebase

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout c√≥digo
      uses: actions/checkout@v5

    - name: Instalar Firebase CLI
      run: npm install -g firebase-tools

    - name: Autenticar no Firebase
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: firebase deploy --only hosting --token "${{ secrets.FIREBASE_TOKEN}}"
